### ISSUE TITLE
compiling on openbsd does not succeed

### ISSUE THREAD

**Issue by gretel** [postmates/cernan#257]
on `openbsd-6.1` calling
`$ cargo run -- --config examples/configs/quickstart.toml`
results in
```
HOST = Some("x86_64-unknown-openbsd")
CFLAGS_x86_64-unknown-openbsd = None
CFLAGS_x86_64_unknown_openbsd = None
HOST_CFLAGS = None
CFLAGS = None
PROFILE = Some("debug")
running "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "include" "-std=c1x" "-Wbad-function-cast" "-Wmissing-prototypes" "-Wnested-externs" "-Wstrict-prototypes" "-fdata-sections" "-ffunction-sections" "-pedantic" "-pedantic-errors" "-Wall" "-Werror" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-declarations" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-Wno-cast-align" "-fstack-protector" "-g3" "-D_XOPEN_SOURCE=700" "-c" "-o/home/tom/src/cernan/target/debug/build/ring-e4465ecc422b5845/out/cmp.o" "crypto/bn/cmp.c"

--- stderr
cc1: error: unrecognized command line option "-Wenum-compare"
cc1: error: unrecognized command line option "-std=c1x"
cc1: warnings being treated as errors
cc1: warning: -Wuninitialized is not supported without -O
thread '<unnamed>' panicked at 'execution failed', /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.7.5/build.rs:720
```

looks like the compiler is called with some flags that openbsd does not support for whatever reason. let me know what else you need or how i could help. regards

**Comment by blt** [comment]
Ah, hmm, looks like from 

    thread '<unnamed>' panicked at 'execution failed', /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.7.5/build.rs:720

That a dependency of cernan is failing. I'm breaking cernan's compilation up into features which'll help with this but the underlying problem will remain. Can you pull https://github.com/briansmith/ring and see if doing a `cargo build` there fails in a similar way? If so, an issue will need to be made on that project. 

Related to #177.

**Comment by gretel** [comment]
hum, looks worse to me..
```
~/src/ring$ cargo build
warning: unused manifest key: package.categories
warning: unused manifest key: package.categories
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading libc v0.2.22
 Downloading untrusted v0.5.0
 Downloading deque v0.3.2
 Downloading num_cpus v1.4.0
   Compiling lazy_static v0.2.8
   Compiling libc v0.2.22
   Compiling untrusted v0.5.0
   Compiling gcc v0.3.45
error: struct field shorthands are unstable (see issue #37340)
   --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/untrusted-0.5.0/src/untrusted.rs:313:21
    |
313 |             Slice { bytes }
    |                     ^^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/untrusted-0.5.0/src/untrusted.rs:327:51
    |
327 |             self.bytes.get(r).map(|bytes| Slice { bytes })
    |                                                   ^^^^^

error: aborting due to 2 previous errors

Build failed, waiting for other jobs to finish...
error: Could not compile `untrusted`.

To learn more, run the command again with --verbose.
```

**Comment by blt** [comment]
@gretel it's been a minute. Has the situation changed at all?

**Comment by blt** [comment]
I'm going to close this issue. If the problem still exists, please do re-open it.
