### ISSUE TITLE
Internal Source With No Forwards Fails to Shutdown Cleanly

### ISSUE THREAD

**Issue by pulltab** [postmates/cernan#372]
Configs such as the following result in a panic when SIGINT is processed by the main cernan thread:

```data-directory = "/tmp/cernan"

flush-interval = 2

[sources]

  [sources.statsd.primary]
  enabled = true
  port = 8125
  forwards = ["sinks.console"]

[sinks]
  [sinks.console]
  bin_width = 1```

Resulting panic:

```$ RUST_BACKTRACE=1 cargo run -- -vvvv --config examples/configs/barf.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/cernan -vvvv --config examples/configs/barf.toml`
[cernan][111][2017-12-20T02:28:03.503826+00:00][INFO] cernan - 0.8.6
[mio::sys::unix::kqueue][95][2017-12-20T02:28:03.504467+00:00][TRACE] registering; token=Token(18446744073709551615); interests=Readable
[mio::sys::unix::kqueue][95][2017-12-20T02:28:03.504569+00:00][TRACE] registering; token=Token(18446744073709551615); interests=Readable
[cernan][48][2017-12-20T02:28:03.504609+00:00][TRACE] Populating sender from "sources.statsd.primary" to "sinks.console"
[mio::poll][784][2017-12-20T02:28:03.504578+00:00][TRACE] registering with poller
[mio::poll][784][2017-12-20T02:28:03.504777+00:00][TRACE] registering with poller
[mio::sys::unix::kqueue][95][2017-12-20T02:28:03.504896+00:00][TRACE] registering; token=Token(18446744073709551615); interests=Readable
[mio::poll][784][2017-12-20T02:28:03.506795+00:00][TRACE] registering with poller
[mio::sys::unix::kqueue][95][2017-12-20T02:28:03.506826+00:00][TRACE] registering; token=Token(0); interests=Readable
[mio::poll][784][2017-12-20T02:28:03.506858+00:00][TRACE] registering with poller
[mio::sys::unix::kqueue][95][2017-12-20T02:28:03.506886+00:00][TRACE] registering; token=Token(1); interests=Readable
[cernan::source::statsd][185][2017-12-20T02:28:03.507034+00:00][INFO] server started on *:8125
^C[cernan][773][2017-12-20T02:28:04.347590+00:00][INFO] Signaling shutdown to "sources.internal"
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/travis/build/rust-lang/rust/src/liballoc/vec.rs:1558:14
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::panicking::panic_bounds_check
  10: <alloc::vec::Vec<T> as core::ops::index::IndexMut<usize>>::index_mut
  11: cernan::util::send
  12: <cernan::source::internal::Internal as cernan::source::Source>::run
  13: cernan::main::{{closure}}
thread 'main' panicked at 'Failed during join!: Any', src/libcore/result.rs:916:4
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
  10: <core::result::Result<T, E>>::expect
  11: cernan::main
  12: __rust_maybe_catch_panic
  13: std::rt::lang_start
  14: main
```

The issue results from an internal source which attempts to send a Shutdown event when `chans` is empty.

**Comment by blt** [comment]
@pulltab this is resolved, yes?

**Comment by pulltab** [comment]
Yes it was.  Closing.
